server:
  port: 0000
spring:
  application:
    name: test
  datasource:
    name: test_ds
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    hikari:
      poolName: hikari数据库连接池
      maximumPoolSize: 200
      minimum-idle: 5
      autoCommit: true
      idleTimeout: 600000  #连接空闲时间
      maxLifetime: 1800000 #一个连接的存活时长ms 30分钟
      connectionTimeout: 10000 #获取连接最大等待时长 30s
#spring:
#  mvc:
#    view:
#      prefix: templates/
#      suffix: .html
#  datasource:
#          type: com.zaxxer.hikari.HikariDataSource
#          driver-class-name: com.mysql.jdbc.Driver
#          jdbcUrl: jdbc:mysql://localhost:3306/test
#          username: root
#          password: root
#          poolName: hikari数据库连接池
#          maximumPoolSize: 50
#          minimum-idle: 5
#          autoCommit: true
#          idleTimeout: 600000  #连接空闲时间
#          maxLifetime: 1800000 #一个连接的存活时长ms 30分钟
#          connectionTimeout: 5000 #获取连接最大等待时长 5s

#sharding:
#  jdbc:
#    datasource:
#      names: hahaha
#      hahaha:
#        type: com.zaxxer.hikari.HikariDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        jdbcUrl: jdbc:mysql://localhost:3306/test
#        username: root
#        password: root
#        poolName: hikari数据库连接池
#        maximumPoolSize: 50
#        minimum-idle: 5
#        autoCommit: true
#        idleTimeout: 600000  #连接空闲时间
#        maxLifetime: 1800000 #一个连接的存活时长ms 30分钟
#        connectionTimeout: 5000 #获取连接最大等待时长 5s
#    config:
#      sharding:
#        tables:
#          admin:
#            actual-data-nodes: hahaha.admin_${0..2}
#            table-strategy:
#              standard:
#                sharding-column: id
#                preciseAlgorithmClassName: com.example.demo.sharding.MyAlgorithm