package com.example.demo.mapper;

import com.example.demo.vo.Admin;

public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Fri Sep 20 14:54:28 CST 2019
     */
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbg.generated Fri Sep 20 14:54:28 CST 2019
     */
    int insertSelective(Admin record);

    Admin selectByPrimaryKey(String id);
}